from __future__ import annotations

import os
from typing import Mapping

DEFAULT_COPILOT_LOCALE = os.getenv("COPILOT_LOCALE", "fr")


COPILOT_STRINGS: Mapping[str, Mapping[str, str]] = {
    "fr": {
        "label_health_score": "Score de santé",
        "label_risk_score": "Score de risque",
        "label_anomalies": "Anomalies récentes",
        "label_latest_temperature": "Température",
        "label_latest_vibration": "Vibrations",
        "label_motor_speed": "Vitesse du moteur",
        "label_machines": "Machines",
        "label_with_telemetry": "Avec télémétrie",
        "label_average_health": "Score de santé moyen",
        "label_pending_reservations": "Réservations en attente",
        "label_pending": "En attente",
        "label_approved": "Approuvées",
        "label_rejected": "Rejetées",
        "label_today": "Aujourd'hui",
        "label_machine_health": "{machine} - score de santé",
        "label_machine_risk": "{machine} - niveau de risque",
        "unit_events": "événements",
        "unit_anomalies": "anomalies",
        "status_available": "disponible",
        "status_in_use": "en utilisation",
        "status_maintenance": "en maintenance",
        "status_out_of_service": "hors service",
        "anomaly_normal": "normal",
        "anomaly_warning": "avertissement",
        "anomaly_critical": "critique",
        "anomaly_no_data": "aucune donnée",
        "risk_low": "faible",
        "risk_medium": "moyen",
        "risk_high": "élevé",
        "risk_unknown": "inconnu",
        "trend_rising": "en hausse",
        "trend_stable": "stable",
        "trend_unknown": "inconnue",
        "example_summary": "Résume l'activité d'aujourd'hui.",
        "example_highest_risk": "Quelle machine présente le risque le plus élevé ?",
        "example_anomalies": "Affiche les anomalies récentes.",
        "example_health": "Explique l'état de santé de CNC_1.",
        "example_compare": "Compare CNC_1 et Printer_1.",
        "machine_not_found_answer": "Je n'ai pas trouvé {label} dans la base actuelle des machines du FabLab ; je ne peux donc pas l'analyser.",
        "machine_not_found_label": "cette machine",
        "machine_not_found_recommendation": "Vérifiez le nom de la machine ou demandez un résumé du parc.",
        "help_answer": "Je peux résumer l'activité du FabLab, expliquer l'état de santé des machines, identifier les machines à risque élevé, comparer les machines, lister les anomalies récentes et synthétiser l'état des réservations.",
        "try_example": "Essayez : {example}",
        "unknown_low_confidence": "Je ne suis pas suffisamment sûr pour classer cette question d'administration.",
        "unknown_no_model": "L'artefact du classificateur d'intentions supervisé n'est pas disponible ; je ne peux donc pas classer cette question de manière fiable.",
        "unknown_suffix": "Veuillez utiliser l'un des types de questions pris en charge par l'assistant de maintenance.",
        "summary_answer": "Le FabLab compte {total} machines, dont {with_telemetry} disposent d'une télémétrie. Le monitoring IA actuel indique {normal} machines normales, {warning} en avertissement et {critical} critiques. {pending} réservations sont en attente et {today} réservations sont planifiées aujourd'hui.",
        "summary_review_risky": "Examinez les machines en avertissement ou critiques avant d'approuver des sessions longues.",
        "summary_continue": "Poursuivez le monitoring de routine.",
        "observed_status": "{machine} est {status}",
        "observed_anomaly": "l'état des anomalies est {status}",
        "observed_health": "le score de santé est de {score} %",
        "observed_risk": "le risque de maintenance est de {score}/100",
        "observed_telemetry": "la dernière télémétrie indique {temperature:.1f} C, {vibration:.2f} mm/s de vibrations et {speed:.0f} tr/min",
        "observed_trends": "les tendances récentes sont : température {temperature_trend} et vibrations {vibration_trend}",
        "machine_status_answer": "Faits observés : {facts}. Analyse : le niveau de risque actuel est {risk_level}.",
        "health_no_factor": "aucun facteur de score élevé dans l'évaluation actuelle",
        "health_factor": "{label} : {score}/{weight}",
        "health_answer": "Faits observés : {facts}. Analyse : l'état de santé de {machine} est influencé par {factors}. Recommandation : utilisez cette analyse comme aide à la décision et vérifiez-la au prochain cycle de télémétrie.",
        "no_risk_ranking": "Aucune machine ne dispose encore d'une télémétrie suffisante pour classer le risque de maintenance.",
        "publish_telemetry": "Publiez de la télémétrie avant d'utiliser le classement des risques.",
        "highest_risk_answer": "{machine} présente actuellement le risque de maintenance observé le plus élevé ({score}/100, {risk_level}). Faits observés : {facts}.",
        "compare_need_two": "Au moins deux machines sont nécessaires pour établir une comparaison.",
        "compare_add_machine": "Ajoutez ou sélectionnez une autre machine, puis reposez la question.",
        "compare_answer": "Comparaison : {first} présente un score de santé de {first_health} % et un risque de {first_risk}/100 ; {second} présente un score de santé de {second_health} % et un risque de {second_risk}/100. Les écarts observés proviennent de la télémétrie actuelle, de l'état des anomalies et des facteurs de risque évalués.",
        "no_recent_anomalies": "Aucune anomalie en avertissement ou critique n'est présente dans les évaluations actuelles des machines.",
        "continue_collecting": "Continuez à collecter la télémétrie et consultez régulièrement le tableau de bord.",
        "recent_anomalies_answer": "Synthèse des anomalies récentes : {names} présentent des signaux d'avertissement ou critiques dans l'évaluation actuelle.",
        "no_maintenance_recommendation": "Aucune recommandation de maintenance ne peut être générée car la télémétrie des machines n'est pas encore disponible.",
        "collect_telemetry": "Collectez la télémétrie avant de prendre des décisions de maintenance.",
        "maintenance_answer": "Faits observés : {facts}. Action recommandée : {action}",
        "reservation_answer": "Synthèse des réservations : {total} réservations au total, {pending} en attente, {approved} approuvées et {today} planifiées aujourd'hui.",
        "review_pending": "Examinez les réservations en attente avant la prochaine session du laboratoire.",
        "no_pending_action": "Aucune action sur les réservations n'est requise pour le moment.",
        "empty_message": "Le message ne peut pas être vide",
        "predictive_no_telemetry": "Aucune télémétrie n'a encore été reçue. Publiez des données capteurs ou des mises à jour MQTT pour activer le monitoring IA.",
        "factor_temperature": "Charge thermique",
        "factor_vibration": "Vibrations mécaniques",
        "factor_runtime": "Utilisation cumulée",
        "factor_errors": "Historique d'erreurs récent",
        "factor_trend": "Tendance télémétrique",
        "detail_temperature": "La plage de fonctionnement normale reste sous {threshold:.0f} C pour cette famille de machines.",
        "detail_vibration": "Des vibrations persistantes au-dessus de {threshold:.1f} mm/s augmentent le risque de maintenance.",
        "detail_runtime": "La maintenance préventive est généralement planifiée autour de {hours:.0f} h.",
        "detail_errors": "Des erreurs répétées dans la télémétrie récente augmentent fortement le risque de panne.",
        "detail_trend_insufficient": "L'historique de télémétrie est encore insuffisant pour évaluer la tendance récente.",
        "detail_trend_stable": "La télémétrie récente reste stable par rapport aux mesures précédentes.",
        "detail_trend_rising": "La température et les vibrations augmentent par rapport à la fenêtre précédente (+{temp:.1f} C, +{vibration:.2f} mm/s).",
        "rec_healthy": "{machine} fonctionne normalement. Maintenez l'inspection de routine et continuez à collecter la télémétrie.",
        "rec_high_factor": "{machine} doit être inspectée avant la prochaine session étudiante. Priorisez {factor} et vérifiez les composants critiques.",
        "rec_high": "{machine} doit être inspectée avant la prochaine session étudiante.",
        "rec_medium_factor": "Planifiez bientôt une maintenance préventive pour {machine}. Concentrez-vous sur {factor} et surveillez les prochaines données télémétriques.",
        "rec_medium": "Planifiez bientôt une maintenance préventive pour {machine}.",
        "rec_low_observe": "{machine} reste utilisable, mais gardez-la sous observation et vérifiez le prochain cycle de télémétrie.",
        "rec_pause": "Suspendez les sessions non essentielles jusqu'à ce qu'un administrateur examine l'état de la machine.",
        "rec_preventive": "Planifiez une inspection préventive avant une utilisation étudiante prolongée.",
        "rec_temperature": "Continuez à surveiller la température ; inspectez la machine si la tendance à la hausse persiste.",
        "rec_vibration": "Surveillez les vibrations lors des prochaines mesures et inspectez la machine si elles restent élevées.",
        "rec_motor": "Vérifiez la stabilité de la vitesse moteur lors d'un essai contrôlé.",
        "rec_anomalies": "Examinez les anomalies récentes et comparez-les avec le prochain cycle de télémétrie.",
        "rec_runtime": "Envisagez une maintenance de routine, car la durée d'utilisation déclarée est élevée.",
        "rec_error": "Vérifiez le dernier indicateur d'erreur de la machine avant d'approuver de nouveaux travaux.",
        "ml_rec_critical": "Arrêtez ou isolez la machine et planifiez une inspection immédiate avant la prochaine session FabLab.",
        "ml_rec_maintenance": "Planifiez bientôt une maintenance préventive et surveillez attentivement les prochaines données télémétriques.",
        "ml_rec_monitor": "La machine peut rester disponible, mais gardez-la sous surveillance et analysez les tendances des capteurs.",
        "ml_rec_healthy": "La machine semble saine. Poursuivez l'exploitation normale et l'inspection de routine.",
        "anomaly_reason_temperature_critical": "La température est entrée dans la plage critique pour ce profil de machine.",
        "anomaly_reason_temperature_drift": "La température dépasse la base de fonctionnement habituelle.",
        "anomaly_reason_vibration_critical": "Les vibrations se situent dans une plage critique et peuvent indiquer une usure mécanique.",
        "anomaly_reason_vibration_drift": "Les vibrations dépassent la plage normale observée dans la télémétrie récente.",
        "anomaly_reason_status_conflict": "La machine signale un mouvement alors que son état n'est pas opérationnel.",
        "anomaly_reason_overspeed": "La vitesse du moteur dépasse la plage sûre pour ce profil de machine.",
        "anomaly_reason_repeated_errors": "Des indicateurs d'erreur répétés ont été signalés dans la télémétrie récente.",
        "anomaly_reason_stale_telemetry": "La télémétrie est ancienne ; l'évaluation IA peut ne pas refléter l'état actuel de la machine.",
    },
    "en": {
        "label_health_score": "Health score",
        "label_risk_score": "Risk score",
        "label_anomalies": "Recent anomalies",
        "label_latest_temperature": "Temperature",
        "label_latest_vibration": "Vibration",
        "label_motor_speed": "Motor speed",
        "label_machines": "Machines",
        "label_with_telemetry": "With telemetry",
        "label_average_health": "Average health",
        "label_pending_reservations": "Pending reservations",
        "label_pending": "Pending",
        "label_approved": "Approved",
        "label_rejected": "Rejected",
        "label_today": "Today",
        "label_machine_health": "{machine} health",
        "label_machine_risk": "{machine} risk",
        "unit_events": "events",
        "unit_anomalies": "anomalies",
        "status_available": "available",
        "status_in_use": "in use",
        "status_maintenance": "under maintenance",
        "status_out_of_service": "out of service",
        "anomaly_normal": "normal",
        "anomaly_warning": "warning",
        "anomaly_critical": "critical",
        "anomaly_no_data": "no data",
        "risk_low": "low",
        "risk_medium": "medium",
        "risk_high": "high",
        "risk_unknown": "unknown",
        "trend_rising": "rising",
        "trend_stable": "stable",
        "trend_unknown": "unknown",
        "example_summary": "Summarize today's activity.",
        "example_highest_risk": "Which machine has the highest risk?",
        "example_anomalies": "Show recent anomalies.",
        "example_health": "Explain CNC_1 health.",
        "example_compare": "Compare CNC_1 and Printer_1.",
        "machine_not_found_answer": "I could not find {label} in the current FabLab machine database, so I cannot analyze it.",
        "machine_not_found_label": "that machine",
        "machine_not_found_recommendation": "Check the machine name or ask for a fleet summary.",
        "help_answer": "I can summarize FabLab activity, explain machine health, identify high-risk machines, compare machines, list recent anomalies, and summarize reservation status.",
        "try_example": "Try: {example}",
        "unknown_low_confidence": "I am not confident enough to classify that admin question.",
        "unknown_no_model": "The supervised intent-classifier artifact is not available, so I cannot safely classify that question.",
        "unknown_suffix": "Please use one of the supported maintenance copilot question types.",
        "summary_answer": "The FabLab has {total} machines, with telemetry available for {with_telemetry}. Current AI monitoring shows {normal} normal, {warning} warning, and {critical} critical machines. There are {pending} pending reservations and {today} reservations scheduled today.",
        "summary_review_risky": "Review warning or critical machines before approving long sessions.",
        "summary_continue": "Continue routine monitoring.",
        "observed_status": "{machine} status is {status}",
        "observed_anomaly": "anomaly status is {status}",
        "observed_health": "health score is {score}%",
        "observed_risk": "maintenance risk is {score}/100",
        "observed_telemetry": "latest telemetry is {temperature:.1f} C, {vibration:.2f} mm/s vibration, {speed:.0f} rpm",
        "observed_trends": "recent trends are temperature {temperature_trend} and vibration {vibration_trend}",
        "machine_status_answer": "Observed facts: {facts}. Inference: current risk level is {risk_level}.",
        "health_no_factor": "no elevated scored factor in the current assessment",
        "health_factor": "{label}: {score}/{weight}",
        "health_answer": "Observed facts: {facts}. Inference: {machine}'s health is influenced by {factors}. Recommendation: use this as decision support and verify with the next telemetry cycle.",
        "no_risk_ranking": "No machine has enough telemetry to rank maintenance risk yet.",
        "publish_telemetry": "Publish telemetry before using risk ranking.",
        "highest_risk_answer": "{machine} currently has the highest observed maintenance risk ({score}/100, {risk_level}). Observed facts: {facts}.",
        "compare_need_two": "At least two machines are required for comparison.",
        "compare_add_machine": "Add or select another machine, then ask again.",
        "compare_answer": "Comparison: {first} has health {first_health}% and risk {first_risk}/100; {second} has health {second_health}% and risk {second_risk}/100. Observed differences come from current telemetry, anomaly status, and scored risk factors.",
        "no_recent_anomalies": "No warning or critical anomalies are present in the current machine assessments.",
        "continue_collecting": "Continue collecting telemetry and review the dashboard regularly.",
        "recent_anomalies_answer": "Recent anomaly summary: {names} have warning or critical signals in the current assessment.",
        "no_maintenance_recommendation": "No maintenance recommendation can be generated because machine telemetry is not available yet.",
        "collect_telemetry": "Collect telemetry before making maintenance decisions.",
        "maintenance_answer": "Observed facts: {facts}. Recommended action: {action}",
        "reservation_answer": "Reservation summary: {total} total reservations, {pending} pending, {approved} approved, and {today} scheduled today.",
        "review_pending": "Review pending reservations before the next lab session.",
        "no_pending_action": "No pending reservation action is required right now.",
        "empty_message": "Message cannot be empty",
        "predictive_no_telemetry": "No telemetry has been received yet. Publish sensor data or MQTT updates to enable AI monitoring.",
        "factor_temperature": "Temperature load",
        "factor_vibration": "Mechanical vibration",
        "factor_runtime": "Accumulated usage",
        "factor_errors": "Recent error history",
        "factor_trend": "Telemetry trend",
        "detail_temperature": "Normal operating band stays below {threshold:.0f} C for this machine family.",
        "detail_vibration": "Persistent vibration above {threshold:.1f} mm/s increases maintenance risk.",
        "detail_runtime": "Preventive maintenance is usually scheduled around {hours:.0f} h.",
        "detail_errors": "Repeated error flags in recent telemetry strongly increase the failure risk.",
        "detail_trend_insufficient": "Not enough telemetry history yet to evaluate the recent trend.",
        "detail_trend_stable": "Recent telemetry remains stable compared with the previous readings.",
        "detail_trend_rising": "Temperature and vibration are rising versus the previous window (+{temp:.1f} C, +{vibration:.2f} mm/s).",
        "rec_healthy": "{machine} is operating normally. Keep routine inspection and continue collecting telemetry.",
        "rec_high_factor": "{machine} should be inspected before the next student session. Prioritize {factor} and verify critical components.",
        "rec_high": "{machine} should be inspected before the next student session.",
        "rec_medium_factor": "Plan preventive maintenance soon for {machine}. Focus on {factor} and monitor the next telemetry updates.",
        "rec_medium": "Plan preventive maintenance soon for {machine}.",
        "rec_low_observe": "{machine} remains usable, but keep it under observation and review the next telemetry cycle.",
        "rec_pause": "Pause non-essential sessions until an admin reviews the machine condition.",
        "rec_preventive": "Plan a preventive inspection before extended student use.",
        "rec_temperature": "Continue monitoring temperature; inspect the machine if the rising trend continues.",
        "rec_vibration": "Watch vibration during the next readings and inspect the machine if it remains elevated.",
        "rec_motor": "Review motor-speed stability during a controlled test run.",
        "rec_anomalies": "Review the recent anomaly details and compare them with the next telemetry cycle.",
        "rec_runtime": "Consider scheduling routine maintenance because reported usage duration is high.",
        "rec_error": "Check the latest machine error flag before approving new work.",
        "ml_rec_critical": "Stop or isolate the machine and schedule immediate inspection before the next FabLab session.",
        "ml_rec_maintenance": "Plan preventive maintenance soon and watch the next telemetry updates closely.",
        "ml_rec_monitor": "Machine can remain available, but keep it under monitoring and review sensor trends.",
        "ml_rec_healthy": "Machine appears healthy. Continue normal operation and routine inspection.",
        "anomaly_reason_temperature_critical": "Temperature entered the critical range for this machine profile.",
        "anomaly_reason_temperature_drift": "Temperature is above the usual operating baseline.",
        "anomaly_reason_vibration_critical": "Vibration is in a critical band and may indicate mechanical wear.",
        "anomaly_reason_vibration_drift": "Vibration is above the normal band observed in recent telemetry.",
        "anomaly_reason_status_conflict": "The machine reports motion while its state is not operational.",
        "anomaly_reason_overspeed": "Motor speed is above the safe range for this machine profile.",
        "anomaly_reason_repeated_errors": "Repeated error flags were reported in recent telemetry.",
        "anomaly_reason_stale_telemetry": "Telemetry is stale, so the AI assessment may not reflect the current machine state.",
    },
}


def copilot_text(key: str, **values: object) -> str:
    dictionary = _active_dictionary()
    template = dictionary[key]
    return template.format(**values)


def _active_dictionary() -> Mapping[str, str]:
    return COPILOT_STRINGS.get(DEFAULT_COPILOT_LOCALE, COPILOT_STRINGS["fr"])


def localize_status(value: str) -> str:
    return _active_dictionary().get(f"status_{value}", value)


def localize_anomaly_status(value: str) -> str:
    return _active_dictionary().get(f"anomaly_{value}", value)


def localize_risk_level(value: str) -> str:
    return _active_dictionary().get(f"risk_{value}", value)


def localize_trend(value: str) -> str:
    return _active_dictionary().get(f"trend_{value}", value)
